#ifndef __CONFIG_H
#define __CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip8"
#define EMULATOR_WINDOW_MULTIPLIER 10

#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_DISPLAY_WIDTH 63
#define CHIP8_DISPLAY_HEIGHT 32

#define CHIP8_TOTAL_DATA_REGISTERS 16

#endif
